language: rust
dist: trusty
sudo: required

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - >
    echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json > /dev/null
  - sudo service docker restart

script:
  - >
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&  [ ! -z "${TRAVIS_TAG}" ]; then
      make lint build tag push
    else
      cargo test &&\
        make lint build
    fi

env:
  global:
  - secure: IShDKHqzxvcdnna7RNA4iswvevDq40u8MgKePj/+xXhwEzBBHt7eqa9QXF1mxGNQJdirN6btXs2phZBiochHqsj0Lal/XiKzzEDWjdnPE3SMONn7kCf1BsKpMHa3uX9Ver00sfPkLoADdbUKUpoypHk/Qj+RCmVVLO8xl2F6aWU7t/L55CuPRl/nOWivma0ADl+3JmuKR/M7olAoaSSSKYdq+pcmA2xQRQGZgDXQAhoTK0E8CcLL6voj4Rzyo/YbGO5Kw+iqDgf2uockr1nnFXhIfIo7VnmahK6JWAb9ynkSpP+AdZ33ihlEl+eqQfn8UR9z82FTnsw7P7YiNviRTDLmgJQ43NAC1qx8VhUz3bynjE15LZImQNBfUiJyZBOJoAU9KmrqgP/cqIVMITH41bsdTCkE1NrXmk2RJM3B57wRxrMc8154zMzTc6VRk5wFRxCD8MEeViYoohnSTz7zdIQ97EBKmxRQorilVw2dZ6QRmntwGu5XY1UwfGQG2n1Zmv9yySTjPdtlDuck8d7FfqDGnA5/PZR1WQIa2heJCTNZ1iYtehW8djO+1TtGcSWoyMBEKXks3Ima8je5rIC43qaUILuh61HeJ2dl0Dp0M4YOyjNH58j7IBjy8tItneVhfVXp71IcZA+liyvO8tN9wjqXV754D2sNDCjYBEi/4GI=
  - secure: yiDPaBgTu6ieKEsJnsrePJ0pGfALOg8EGILkUNmWJIebfcsXDka8vxL7v8nCvRO3VDP/G3ngPjHwZxEaxZdHJRLCzp+P6E3S4vSLw6gPFRy0dYrOrtKWJWEd45NouiPS60ULXad7ZnsU4/SxfC7Pb+y7GHnrYg8vEEw+jFxwZo8cD6rrxT9QFwN2sKzU22XiH8NCjUqJfcjd2lk5mu3u32CjfQh55el7QP4iRztM9yrytyYCmanSNj+pkk0BAqVNTvhqokbGkrknxTRIIVPhI/oSln95wL3UnJKrY/BSYDgrH3lcMfOzMQACpobWIvqyBxgKSuCK3lyngKML0X1s9BjEwdk7VkNOlup4KkoH2kPaka/kxCDkuOKxlVIY0hRtRPTbOZLQqj1fgAa/lqU+JUSltJDYXePsLIpvzKi169jEIwDK+sLHeG0QoY7gDQE4lv8whc45ILn3kBJjPWX7VSks+URhlgSk5v9xa7OSzOAGUH6NJbM6hYbLUdXjVoE3I4deDZql8vL9DI2gioRJfCMf8AYgtLNMmhu9nl9HGw0EBaGSONtrZhFInW1mgwCC3mKC30ylqJiQtnysFd6zEI9MghHY5XB0MxvWvnht5MXp/8jR9Vmx/evNNIxjh17PhyNChx+/L5rRViGXi54EFl2E7Vq4Afd6FcG+hpdDxqs=

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo