language: c

sudo: required

addons:
  apt:
    packages:
      - docker-ce

script:
  - make lint build tag push

env:
  global:
  - secure: E8jqaHrIhlhUbGACgny1mhyKNhlTF2x6o4MgmHfUnhWHxOZloENAyGuSAmRNqrMz0e+nHbUS4bmGJkbSLiqkGFThtHw+FyV/9NZdLBTgJD5w/dgfKXhYQkYYJnXoy8QLf7D89P9G1X0gEMDkTohkJ1k6Tq/2Jmxdrt53dO6gYte73KJ29n9H51BE7Ln/xINf7YlnATcDjefnkgl4q6oYzaZ7GEtLzqW4iOTS983iBc2sRk+tu8ZrgGB+0uGcvXlAqSFOXEzcfIo/eQ32rPpjgaAjg+pgYJUD63Be2r1MVyZ1zUx+gfhJR1wEl0lc3Fl8mejDjeYkJaa3ZX2/byfV+Fgw7s0NjBeeKdDHYdcdDK8OohDJLSuIOHHO8ph3mqzkOjLPLV9V7gcotdqNOghhGQP7B5Pbx9p4FuGdGcaWkCAblc5CHE0eKLnJ/2JgnNcAtuTVqOZfErwLPO71D66cNQPx4AJcIBrhCS280pbR7nAeFVphgwtfHzC/Fhl/CcZspY/6vgm6+4r8ayjVh2TcBGxWQYq2AwctqbtUI9e+tLPs+M23TfhTCOtX8n9hd4mDe2F7KQW3ecmjzHYSi43aukUjrOrTTjASt85hsddgvIwnPGGLkYDcfniejKrVjxgrjUedP4dceTTv0RmazrGmDznw18k8i6CyUDvc1+mFqDY=
  - secure: IcxnUWHYrgk4i1bX7Rvuh5pKXv5YJ1BQxJwOqnT6/ijRtnriHHTc60OeEIaKle7TgMvZb9HWBW7L1/Z1/aP4MjFooro9vfFT0DKQHNLxBKVL0TCURjuvPO0pv2mW0/8BCl7y5mYcl46yfa4MdI0vehsGQBoSpyn9guDTMiyG11JflsV3HxGWgoACTko8z1umWN09ZFx2N8UQtXk/cpEu+Owutvx1XqnjkWXDqUomasr/uOpkePR8WEHbdCk1WMKKSltGqCPV2DA2LPNHivYw7OQck2WrT81nvU+mVPFcPUQmSLIHdCOhki5V6aTx8udlrYAKAYfKY3DoelkvrQC6B0VyeNLzDv82IxBiUANlOPrMxnxAiinDBbii+73TQxwFQAVOyxQZMszbCBPWTbFYQRgxCwlgjElq3NPuRm9HySkflYQtFKqNsWrpv1ylR/emdLK0omab+IL781qHAYp2B2I3S37lsNeyn/8DJoMz7Iy/0R+rMNyiGZKqxMJZzT/pqkso0PLZUjx6dPJWn2EdcIf/wNfs/Wwe+dAkFpIHkhzNxbh/IvmvJRyQsRva6XKnIRUxSC2DQA4T1rsU6h4f9Nfkg0s78wCnJr1lL74RUbcxMZfUBC/QnOLa1lLPrY/dZC/RluX/KPbiadYuLlNpmgPzyCVodUD1RC47G8nYeE8=
