[package]
name = "taps3"
version = "0.1.0"
authors = ["lloyd.chan <lloydmeta@gmail.com>"]

[dependencies]
rusoto_core = "0.28.0"
rusoto_s3 = "0.28.0"
chrono = "0.4"
clap = "2.26"
openssl-probe = "0.1"

[profile.release]
opt-level = 3
debug = false
lto = true